In [1]:
function parse_file(file)
    instancia = open(file)
    arr  = []
    for line in eachline(instancia)
        push!(arr, line)
    end
    close(instancia)
    
    vertices = []
    premios = []
    flag_vertices = true
    for line in arr[8:length(arr)]
        if startswith(line, "DEMAND_SECTION")
            flag_vertices = false
        elseif startswith(line, "DEPOT_SECTION")
            break
        elseif flag_vertices
            x, y = split(line)[2:3]
            x = parse(Int32, x)
            y = parse(Int32, y)
            push!(vertices, (x,y))
        else
            premio = split(line)[2]
            premio = parse(Int32, premio)
            push!(premios, premio)

        end
    end
    return (vertices, premios)
end

parse_file (generic function with 1 method)

In [2]:
function get_distancias(vertices)
    cardinalidade = length(vertices)
    distancias = zeros(cardinalidade, cardinalidade)
    for i in 1:cardinalidade
        for j in 1:cardinalidade
            distancia = ((vertices[i][1] - vertices[j][1])^2 + (vertices[i][2] - vertices[j][2])^2)^(0.5)
            distancias[i, j] =  round(distancia)
        end
    end
    return distancias
end

get_distancias (generic function with 1 method)

In [3]:
function get_arestas(vertices)
    cardinalidade = length(vertices)
    arestas = zeros(Int8, cardinalidade, cardinalidade)
    return arestas
end

get_arestas (generic function with 1 method)

In [5]:
[1, "a"]

2-element Array{Any,1}:
 1
  "a"

In [4]:
file = "instancias/A-n32-k5.vrp"
vertices, premios = parse_file(file)

(Any[(82, 76), (96, 44), (50, 5), (49, 8), (13, 7), (29, 89), (58, 30), (84, 39), (14, 24), (2, 39)  …  (5, 42), (42, 9), (61, 62), (9, 97), (80, 55), (57, 69), (23, 15), (20, 70), (85, 60), (98, 5)], Any[0, 19, 21, 6, 19, 7, 12, 16, 6, 16  …  4, 8, 24, 24, 2, 20, 15, 2, 14, 9])

In [56]:
distancias = get_distancias(vertices)

32×32 Array{Float64,2}:
 0.0    35.0    78.0    76.0    98.0    …  85.0    62.0    16.0     73.0
 1.0e7   0.0    60.0    59.0    91.0       79.0    80.0    19.0     39.0
 1.0e7   1.0e7   0.0     3.0    37.0       29.0    72.0    65.0     48.0
 1.0e7   1.0e7   1.0e7   0.0    36.0       27.0    68.0    63.0     49.0
 1.0e7   1.0e7   1.0e7   1.0e7   0.0       13.0    63.0    89.0     85.0
 1.0e7   1.0e7   1.0e7   1.0e7   1.0e7  …  74.0    21.0    63.0    109.0
 1.0e7   1.0e7   1.0e7   1.0e7   1.0e7     38.0    55.0    40.0     47.0
 1.0e7   1.0e7   1.0e7   1.0e7   1.0e7     66.0    71.0    21.0     37.0
 1.0e7   1.0e7   1.0e7   1.0e7   1.0e7     13.0    46.0    80.0     86.0
 1.0e7   1.0e7   1.0e7   1.0e7   1.0e7     32.0    36.0    86.0    102.0
 1.0e7   1.0e7   1.0e7   1.0e7   1.0e7  …  70.0    21.0    85.0    122.0
 1.0e7   1.0e7   1.0e7   1.0e7   1.0e7     19.0    62.0    94.0     93.0
 1.0e7   1.0e7   1.0e7   1.0e7   1.0e7     84.0    80.0    15.0     47.0
 ⋮                         

In [47]:
arestas = get_arestas(vertices)

32×32 Array{Int8,2}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     

In [37]:
# teste
for file in readdir("instancias"; join=true)
    #println(file)
    vertices, premios = parse_file(file)
    distancias = get_distancias(vertices)
    arestas = get_arestas(vertices)
    if !(size(distancias)[1] == size(vertices)[1])
        println("Erro ", file)
    end
end